name: Test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: archlinux/archlinux-repro
          ref: 20240216
          path: archlinux-repro
      - working-directory: archlinux-repro
        run: |
          sudo apt install -y asciidoc systemd-container
          make
          sudo make install
      - run: |
          curl https://archive.archlinux.org/packages/y/yaml-cpp/yaml-cpp-0.8.0-1-x86_64.pkg.tar.zst -o pkg.tar.zst
          archlinux-repro pkg.tar.zst
