name: Test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: df -h
      - run: ps -ef
      - run: free -h
      - run: sudo cat /proc/swaps
      - run: sudo bash -c 'echo $PATH'
